= Iut Blagnac



=  SAE 2.05 / 2.01   Groupe 2A04

Massip, Nabaoui, Quinveros<massip.romain@etu.univ-tlse2.fr, maisonaya@gmail.com, jordan.quinveros.pro@gmail.com>
v1.0, 2022-05-17

== Sommaire
<<id,Presentation générale>>

<<id2,Installation utilisation >>

<<id3,Fonctionnement>>

<<id4, Résultats produits avec jeux d'essai commentés>>




== 1.Presentation générale
La banque DailyBank souhaite développer une application JAVA-Oracle de gestion des comptes clients pour remplacer plusieurs outils obsolètes. Ce développement s’inscrit dans le cadre de la restructuration de ses services bancaires et l’application sera déployée dans les 100 agences que compte son réseau. 



== 2.Installation utilisation 
Pour commencer l'installation de l'application ,il faut dabord mettre en place le workspace sur eclipse . Ensuite il faut exécuter le script sur sqldeveloper



== 3.Fonctionnement
Le projet démarre en lançant application.DailyBankApp. L'application doit permettre a un guichetier de creer un nouveau client et modifier ses informations et de consulter et debiter un compte. Elle doit aussi permettre a un chef d'agence de rendre inactif un client.


== 4. Résultats produits avec jeux d'essai commentés
