# sae2022-bank-2a04
sae2022-bank-2a04 created by GitHub Classroom

Vous devez ici indiquer l'équipe et un petit résumé du projet.

Ayanaboui évite de laisser ton compte github ouvert sur les pcs de l'IUT. J'aurais pu faire de la merde avec.

== Livrables

[cols="1,2,2,5",options=header]
|===
| Date    | Nom         |  Lien                             | Retour
| 03/04   | Gantt V1    |                                                              | Vous deviez faire le gantt de la v1 je ne trouve pas dans votre gantt des phases de correction de bugs, de rédaction des docs... Il faut détailler encore plus.
|         | CdC V1      |                                   |   https://github.com/IUT-Blagnac/sae2022-bank-2a04/blob/main/RetourCDCUv1.adoc
|         | Suivi Projet |                                   |   Je ne peux pas voir vos commits car votre projet est privé... ?
Les issues sont conformes au gantt et affectées mais pas encore hiérarchisées (possible à ce stade).
L'arborescence de répertoire est crée mais il faudra penser à : une répertoire pour le docs, les sources...
Penser aussi à taguer les livrables.
| 22/04  | CdC V2/V3 final|          Lien manquant !!                           |  1,5/2	Manque nom du projet et du client
1/2	De nombreuses fautes de syntaxe et d'orthographe. Numéroter le sommaire comme les paragraphes
1,5/4	Confus, il manque la problématique, les objectifs du projet.
2/4	Trop succinct, présenter les utilisateurs,  donner les aspects techniques de l'appli …
1/4	Confusion j'ai un UC V0 au lieu de V1 et rien sur V2 et V3. Pas d'explications, pas de priorisation des fonctionnalités …
0,5/4	Les contraintes ne sont pas comprises : contraintes techniques (lg, archi …), orga (dates de livraison, organisation de l'équipe, outils collaboratifs, gantt commentés), juridique (RGPD, impact sur votre projet …), règles de gestion pour les fonctionnalités (conditions pour réalise un débit par ex).
	
7,5	/20

|         | Gantt V2    |                               |     
|         | Gantt V3 |         |     
|         | Doc. Tec. V1 |        |    
|         | Doc User V1    |        |retard livraison V1 pour suivi !
|         | Recette V1  |                      | 
|         | Suivi projet|   | 
| 22/05   | Gantt V2  à jour    |       | 
|         | Doc. Util. V1 |         |https://github.com/IUT-Blagnac/sae2022-bank-2a04/blob/main/doc%20utilisateur.adoc         
|         | Doc. Tec. V1 |                |     
|         | Code V1     |                     | 
|         | Recette V1 |                      | 
|         | Gantt V3 à jour   |                      | 
|         | `jar` projet |    | 
| 05/06   | Gantt V3 à Jour  |    |  
|         | Doc. Util. V2 |         |https://github.com/IUT-Blagnac/sae2022-bank-2a04/blob/main/doc%20utilisateur.adoc            
|         | Doc. Tec. V2 |    |     
|         | Code V2     |                       |
|         | Recette V2  |   |
|         | `jar` projet |     |
|12/06   | Gantt V3 à Jour  |    |  
|         | Doc. Util. V3 |         |           
|         | Doc. Tec. V3 |    |     
|         | Code V3     |                       |
|         | Recette V3  |   |
|         | `jar` projet |     |
|===
== Les critères d'évaluation :SAE S2.05 Gestion de projet

=== CDCU
• Page de garde (Version, date, équipe, projet ...), Sommaire
• Présentation du sujet
◦ contexte, objectifs, à quel problème répond-t-il ?
• Analyse de l’existant
• Analyse des besoins incluant V2 et V3
• Analyse des contraintes
◦ techniques & organisationnelles


=== Gestion de projet
Gantts complets, cohérents avec les issues et à jour (tâches, resp., avancements...)
Format (Gantt en pdf, docs en asciidoc) et arborescence du dépôt
Sources versionnées, commit réguliers et commentés...
Gestion du projet sous Github (issues, millestones, avancée ...), prise en compte des remarques dans le readme

